name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  push:
    branches:
      - main
    paths:
      - ".github/workflows/grs.yml"
      - "profile/*.svg"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROFILE_USERNAME: RepGraphics

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ env.PROFILE_USERNAME }}&show_icons=true&theme=default
          path: profile/stats.svg
          token: ${{ secrets.PAT_1 }}

      - name: Generate dark stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ env.PROFILE_USERNAME }}&show_icons=true&theme=dark
          path: profile/stats-dark.svg
          token: ${{ secrets.PAT_1 }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ env.PROFILE_USERNAME }}&layout=compact&langs_count=6&theme=default
          path: profile/top-langs.svg
          token: ${{ secrets.PAT_1 }}

      - name: Generate dark top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ env.PROFILE_USERNAME }}&layout=compact&langs_count=6&theme=dark
          path: profile/top-langs-dark.svg
          token: ${{ secrets.PAT_1 }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
